In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics
from os import listdir
from os.path import isfile, join

In [2]:
path="C:\\Users\\nilu1\\PatternCracking\\acc\\"
pathex=[]
temp = [f for f in listdir(path) if isfile(join(path, f))]
temp.sort()
for i in range(len(temp)):
    st=temp[i]
    if(st[:2]=="27"):
        pathex.append(temp[i])
# print(pathex)

In [3]:
# n -> number of lines in csv file
# actual -> the actual key pressed
n=100
actual=1
x=[]
y=[]
z=[]
temp=pd.read_csv(path+pathex[0])
temp=temp.head(n)
x=list(temp["X"])
y=list(temp["Y"])
z=list(temp["Z"])
maxx=max(x)
minx=min(x)
maxy=max(y)
miny=min(y)
maxz=max(z)
minz=min(z)
data=[[maxx-x[0],minx-x[0],maxy-x[0],miny-x[0],maxz-x[0],minz-x[0]]]
df=pd.DataFrame(data, columns = ['X','XX', 'Y','YY','Z','ZZ'])
df.insert(6, "key", str(pathex[0][-5]))
df

          X         Y         Z key
0  2.561783  0.900223  1.474823   1

In [4]:
for i in range(1,len(pathex)):
    dff=pd.read_csv(path+pathex[i])
    dff=dff.head(n)
    x=list(dff["X"])
    y=list(dff["Y"])
    z=list(dff["Z"])
    maxx=max(x)
    minx=min(x)
    maxy=max(y)
    miny=min(y)
    maxz=max(z)
    minz=min(z)
    data=[[maxx-x[0],minx-x[0],maxy-x[0],miny-x[0],maxz-x[0],minz-x[0]]]
    temp=pd.DataFrame(data, columns = ['X','XX', 'Y','YY','Z','ZZ'])
    temp.insert(6, "key", str(pathex[i][-5]))
    df=df.append(temp,ignore_index = True)
df

           X         Y          Z key
0   2.561783  0.900223   1.474823   1
1   0.256180  0.184357   0.426162   1
2   0.766144  1.142044   1.209076   1
3   5.073318  0.000000   8.793915   1
4   0.624878  0.000000   1.414978   2
5   2.360687  0.000000   4.280823   2
6   1.702286  0.000000   4.024659   2
7   1.218658  0.000000   4.668686   2
8   3.160339  0.000000   7.098801   3
9   3.100494  0.000000   6.438019   3
10  4.900925  1.048660   7.228103   3
11  3.074158  0.000000   4.915299   3
12  3.397369  0.742203   6.974304   4
13  6.234497  0.466873   6.914459   4
14  3.624817  0.337585   7.402863   4
15  3.490738  0.000000  11.235993   4
16  4.699814  0.000000   7.275971   5
17  3.165131  0.000000   7.283173   5
18  2.597717  0.000000   6.890503   5
19  3.141190  0.016769   5.195419   5
20  3.955231  0.000000   5.942413   6
21  3.782837  0.000000   6.794754   6
22  4.343079  0.000000   4.960785   6
23  4.908112  0.332794   6.876145   6
24  5.714951  0.000000   8.631104   7
25  4.017471  0.344772  12.174515   7
26  3.337509  0.000000   8.834610   7
27  6.351822  0.019150   7.563279   7
28  4.230560  0.000000   6.291962   8
29  3.562576  1.395828   5.341476   8
30  5.322311  0.268158   5.453995   8
31  4.458008  0.016769   5.444412   8
32  3.428497  0.000000   6.469147   9
33  4.297592  0.754181   3.957612   9
34  3.948029  0.189148   5.264847   9
35  2.698257  0.694321   4.644760   9
36  6.797150  2.624054   7.644699   0
37  3.454834  0.000000   8.049301   0
38  4.283218  0.000000   6.469132   0
39  4.065353  0.828385   4.975158   0

In [5]:
X = df.iloc[:, 0:6].values
y = df.iloc[:, 6].values

In [6]:
#divide train and test data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [7]:
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [8]:
y_pred = regressor.predict(X_test)

In [9]:
df = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
df

  Actual  Predicted
0      6   5.679133
1      6   5.143587
2      7   3.290834
3      2   3.421936
4      3   4.051151
5      4   3.587823
6      8   5.291416
7      3   4.650216

In [10]:
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 1.5163137858925537
Mean Squared Error: 3.493832753041311
Root Mean Squared Error: 1.8691797005749102