In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn import metrics
from os import listdir
from os.path import isfile, join

In [2]:
path="C:\\Users\\nilu1\\PatternCracking\\acc\\"
pathex=[]
temp = [f for f in listdir(path) if isfile(join(path, f))]
temp.sort()
for i in range(len(temp)):
    st=temp[i]
    if(st[:2]=="27"):
        pathex.append(temp[i])
    if(st[:2]=="10"):
        pathex.append(temp[i])
# print(pathex)

In [3]:
# n -> number of lines in csv file
# actual -> the actual key pressed
# n=130
actual=1
x=[]
y=[]
z=[]
temp=pd.read_csv(path+pathex[0])
x=list(temp["X"])
y=list(temp["Y"])
z=list(temp["Z"])
maxx=max(x)
minx=min(x)
maxy=max(y)
miny=min(y)
maxz=max(z)
minz=min(z)
data=[[maxx-x[0],minx-x[0],maxy-y[0],miny-y[0],maxz-z[0],minz-z[0]]]
df=pd.DataFrame(data, columns = ['X','XX', 'Y','YY','Z','ZZ'])
ind=pathex[0].rfind("_")+3
df.insert(6, "key", str(pathex[0][ind]))
df

          X        XX         Y        YY         Z        ZZ key
0  1.154007 -2.197876  0.574615 -0.620087  2.147598 -4.261688   2

In [4]:
for i in range(1,len(pathex)):
#     print(pathex[i])
    dff=pd.read_csv(path+pathex[i])
    x=list(dff["X"])
    y=list(dff["Y"])
    z=list(dff["Z"])
    maxx=max(x)
    minx=min(x)
    maxy=max(y)
    miny=min(y)
    maxz=max(z)
    minz=min(z)
    print(pathex[i])
#     if(type(maxx)==str or type(maxy)==str or type(maxz)==str or type(minx)==str or type(miny)==str or type(minz)==str):
#         continue
#     if(type(x[0])==str or type(y[0])==str or type(z[0])==str):
#         continue
    data=[[maxx-x[0],minx-x[0],maxy-y[0],miny-y[0],maxz-z[0],minz-z[0]]]
    temp=pd.DataFrame(data, columns = ['X','XX', 'Y','YY','Z','ZZ'])
    ind=pathex[i].rfind("_")+3
    temp.insert(6, "key", str(pathex[i][ind]))
    df=df.append(temp,ignore_index = True)
df

10-Jan-2020_10_12_27_AM21092.csv
10-Jan-2020_10_12_32_AM3845.csv
10-Jan-2020_10_13_11_AM41338.csv
10-Jan-2020_10_13_27_AM51123.csv
10-Jan-2020_10_13_33_AM61534.csv
10-Jan-2020_10_13_36_AM71095.csv
10-Jan-2020_10_13_40_AM81167.csv
10-Jan-2020_10_13_43_AM91066.csv
10-Jan-2020_10_13_47_AM01036.csv
10-Jan-2020_10_13_54_AM11009.csv
10-Jan-2020_10_13_59_AM21378.csv
10-Jan-2020_10_14_03_AM31212.csv
10-Jan-2020_10_14_09_AM4774.csv
10-Jan-2020_10_14_14_AM51063.csv
10-Jan-2020_10_14_18_AM61056.csv
10-Jan-2020_10_14_23_AM71075.csv
10-Jan-2020_10_14_30_AM81669.csv
10-Jan-2020_10_14_35_AM91486.csv
10-Jan-2020_10_14_40_AM01401.csv
10-Jan-2020_10_14_48_AM1984.csv
10-Jan-2020_10_14_53_AM21153.csv
10-Jan-2020_10_14_58_AM31318.csv
10-Jan-2020_10_15_29_AM41282.csv
10-Jan-2020_10_15_35_AM51870.csv
10-Jan-2020_10_15_41_AM61666.csv
10-Jan-2020_10_15_50_AM7-3034.csv
10-Jan-2020_10_15_59_AM82429.csv
10-Jan-2020_10_16_08_AM93459.csv
10-Jan-2020_10_16_22_AM0982.csv
10-Jan-2020_10_16_28_AM11309.csv
10-Jan-2020_10_16_34_AM21731.csv
10-Jan-2020_10_16_40_AM31372.csv
10-Jan-2020_10_16_45_AM41121.csv
10-Jan-2020_10_16_51_AM51837.csv
10-Jan-2020_10_16_57_AM61468.csv
10-Jan-2020_10_17_02_AM71337.csv
10-Jan-2020_10_17_09_AM81015.csv
10-Jan-2020_10_17_14_AM91355.csv
10-Jan-2020_10_17_21_AM01682.csv
10-Jan-2020_10_17_39_AM1798.csv
10-Jan-2020_10_17_48_AM21144.csv
10-Jan-2020_10_17_55_AM31454.csv
10-Jan-2020_10_18_02_AM71269.csv
10-Jan-2020_10_18_07_AM41478.csv
10-Jan-2020_10_18_13_AM51726.csv
10-Jan-2020_10_18_19_AM61822.csv
10-Jan-2020_10_18_24_AM81019.csv
10-Jan-2020_10_18_28_AM91080.csv
10-Jan-2020_10_18_33_AM01001.csv
10-Jan-2020_10_18_38_AM1730.csv
10-Jan-2020_10_18_42_AM2933.csv
10-Jan-2020_10_18_48_AM61293.csv
10-Jan-2020_10_19_07_AM3932.csv
10-Jan-2020_10_19_13_AM4737.csv
10-Jan-2020_10_19_19_AM51666.csv
10-Jan-2020_10_19_24_AM71311.csv
10-Jan-2020_10_19_30_AM81766.csv
10-Jan-2020_10_19_35_AM91566.csv
10-Jan-2020_10_19_41_AM01295.csv
10-Jan-2020_10_19_57_AM11016.csv
10-Jan-2020_10_20_01_AM21104.csv
10-Jan-2020_10_20_06_AM31050.csv
10-Jan-2020_10_20_10_AM4923.csv
10-Jan-2020_10_20_14_AM5948.csv
10-Jan-2020_10_20_19_AM6798.csv
10-Jan-2020_10_20_23_AM7947.csv
10-Jan-2020_10_20_28_AM81383.csv
10-Jan-2020_10_20_32_AM91231.csv
10-Jan-2020_10_20_36_AM01069.csv
10-Jan-2020_10_20_41_AM11250.csv
10-Jan-2020_10_20_45_AM21053.csv
10-Jan-2020_10_20_50_AM31329.csv
10-Jan-2020_10_20_56_AM41187.csv
10-Jan-2020_10_21_01_AM5955.csv
10-Jan-2020_10_21_05_AM61058.csv
10-Jan-2020_10_21_10_AM71128.csv
10-Jan-2020_10_21_15_AM81102.csv
10-Jan-2020_10_21_29_AM91009.csv
10-Jan-2020_10_21_34_AM01167.csv
10-Jan-2020_10_22_19_AM1883.csv
10-Jan-2020_10_22_23_AM2948.csv
10-Jan-2020_10_22_27_AM31264.csv
10-Jan-2020_10_22_30_AM4883.csv
10-Jan-2020_10_22_33_AM5900.csv
10-Jan-2020_10_22_37_AM6951.csv
10-Jan-2020_10_22_40_AM7724.csv
10-Jan-2020_10_22_44_AM81014.csv
10-Jan-2020_10_22_47_AM9901.csv
10-Jan-2020_10_22_51_AM01141.csv
10-Jan-2020_10_25_00_AM12050.csv
10-Jan-2020_10_25_04_AM21143.csv
10-Jan-2020_10_25_09_AM31275.csv
10-Jan-2020_10_25_14_AM4978.csv
10-Jan-2020_10_25_18_AM51230.csv
10-Jan-2020_10_25_23_AM61231.csv
10-Jan-2020_10_25_27_AM71102.csv
10-Jan-2020_10_25_33_AM81008.csv
10-Jan-2020_10_25_37_AM91005.csv
10-Jan-2020_10_25_42_AM01364.csv
10-Jan-2020_10_25_52_AM1791.csv
10-Jan-2020_10_25_56_AM2998.csv
10-Jan-2020_10_26_01_AM31335.csv
10-Jan-2020_10_26_06_AM41122.csv
10-Jan-2020_10_26_11_AM51138.csv
10-Jan-2020_10_26_15_AM61066.csv
10-Jan-2020_10_26_19_AM7667.csv
10-Jan-2020_10_26_23_AM81011.csv
10-Jan-2020_10_26_28_AM9940.csv
10-Jan-2020_10_26_31_AM0858.csv
10-Jan-2020_10_26_47_AM1609.csv
10-Jan-2020_10_26_51_AM21583.csv
10-Jan-2020_10_26_56_AM31811.csv
10-Jan-2020_10_27_01_AM4954.csv
10-Jan-2020_10_27_06_AM51757.csv
10-Jan-2020_10_27_10_AM61741.csv
10-Jan-2020_10_27_16_AM71551.csv
10-Jan-2020_10_27_21_AM81554.csv
10-Jan-2020_10_27_26_AM9954.csv
10-Jan-2020_10_27_30_AM01300.csv
10-Jan-2020_10_27_56_AM1796.csv
10-Jan-2020_10_28_02_AM2967.csv
10-Jan-2020_10_28_07_AM31200.csv
10-Jan-2020_10_28_12_AM4719.csv
10-Jan-2020_10_28_17_AM51766.csv
10-Jan-2020_10_28_23_AM61652.csv
10-Jan-2020_10_28_28_AM71117.csv
10-Jan-2020_10_28_34_AM81951.csv
10-Jan-2020_10_28_40_AM91489.csv
10-Jan-2020_10_28_47_AM01661.csv
10-Jan-2020_10_29_14_AM11713.csv
10-Jan-2020_10_29_19_AM21062.csv
10-Jan-2020_10_29_23_AM31397.csv
10-Jan-2020_10_29_27_AM41016.csv
10-Jan-2020_10_29_33_AM52014.csv
10-Jan-2020_10_29_39_AM61517.csv
10-Jan-2020_10_29_46_AM7897.csv
10-Jan-2020_10_29_50_AM81179.csv
10-Jan-2020_10_29_55_AM91029.csv
10-Jan-2020_10_29_58_AM01156.csv
27-Dec-2019_8_29_09_PM1.csv
27-Dec-2019_8_29_46_PM1.csv
27-Dec-2019_8_29_52_PM1.csv
27-Dec-2019_8_29_58_PM1.csv
27-Dec-2019_8_30_29_PM2.csv
27-Dec-2019_8_30_36_PM2.csv
27-Dec-2019_8_30_42_PM2.csv
27-Dec-2019_8_30_48_PM2.csv
27-Dec-2019_8_30_56_PM3.csv
27-Dec-2019_8_31_01_PM3.csv
27-Dec-2019_8_31_07_PM3.csv
27-Dec-2019_8_31_13_PM3.csv
27-Dec-2019_8_31_19_PM4.csv
27-Dec-2019_8_31_23_PM4.csv
27-Dec-2019_8_31_27_PM4.csv
27-Dec-2019_8_31_32_PM4.csv
27-Dec-2019_8_31_38_PM5.csv
27-Dec-2019_8_31_41_PM5.csv
27-Dec-2019_8_31_46_PM5.csv
27-Dec-2019_8_31_49_PM5.csv
27-Dec-2019_8_31_53_PM6.csv
27-Dec-2019_8_31_58_PM6.csv
27-Dec-2019_8_32_04_PM6.csv
27-Dec-2019_8_32_11_PM6.csv
27-Dec-2019_8_32_25_PM7.csv
27-Dec-2019_8_32_30_PM7.csv
27-Dec-2019_8_32_34_PM7.csv
27-Dec-2019_8_32_40_PM7.csv
27-Dec-2019_8_33_10_PM8.csv
27-Dec-2019_8_33_16_PM8.csv
27-Dec-2019_8_33_22_PM8.csv
27-Dec-2019_8_33_34_PM8.csv
27-Dec-2019_8_33_43_PM9.csv
27-Dec-2019_8_33_58_PM9.csv
27-Dec-2019_8_34_10_PM9.csv
27-Dec-2019_8_34_16_PM9.csv
27-Dec-2019_8_34_36_PM0.csv
27-Dec-2019_8_34_41_PM0.csv
27-Dec-2019_8_34_52_PM0.csv
27-Dec-2019_8_34_58_PM0.csv

            X        XX         Y        YY         Z        ZZ key
0    1.154007 -2.197876  0.574615 -0.620087  2.147598 -4.261688   2
1    0.538696 -0.802063  0.110138 -0.304062  1.532288 -1.745376   2
2    0.481247 -3.090912  1.491592 -0.988800  1.187515 -3.332733   5
3    0.632080 -2.334335  1.017532 -0.248993  1.326386 -2.688690   8
4    1.048660 -1.596939  1.204285 -0.960068  2.286469 -1.635238   3
..        ...       ...       ...       ...       ...       ...  ..
175  2.698257  0.000000  0.694321 -2.212250  4.644760  0.000000   9
176  6.797150  0.000000  2.624054 -3.677490  7.644699 -2.116470   0
177  3.454834 -0.471649  0.000000 -3.040634  8.049301  0.000000   0
178  4.587280 -0.270554  0.000000 -4.747696  6.469132 -1.146820   0
179  4.065353 -0.126892  1.946487 -3.246536  4.975158 -2.178726   0

[180 rows x 7 columns]

In [5]:
X = df.iloc[:, 0:6].values
y = df.iloc[:, 6].values

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=0)

In [7]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [8]:
regressor = RandomForestRegressor(n_estimators=20, random_state=1)
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
df = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
df

   Actual  Predicted
0       7       4.45
1       7       4.65
2       2       3.55
3       6       6.55
4       7       4.90
5       3       4.70
6       1       5.20
7       3       4.85
8       6       7.05
9       0       4.90
10      1       5.45
11      4       5.65
12      5       3.60
13      4       4.60
14      6       6.15
15      5       4.55
16      7       4.00
17      1       4.25

In [9]:
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 2.0972222222222223
Mean Squared Error: 6.268750000000001
Root Mean Squared Error: 2.5037471917108567